# Generated by Django 2.1.4 on 2018-12-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='postagem',
        ),
    ]
