# Generated by Django 2.1.4 on 2018-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181229_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='init',
            field=models.BooleanField(default=True),
        ),
    ]
