# Generated by Django 2.1.4 on 2018-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
