# Generated by Django 2.1.4 on 2019-02-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='usuario',
        ),
    ]
