# Generated by Django 2.1.5 on 2019-02-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190203_1032'),
        ('posts', '0010_comments_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('GO', 'Gostei'), ('VM', 'Vamos'), ('HR', 'Horrivel'), ('QR', 'Quero'), ('LG', 'Legal'), ('VU', 'Vou'), ('BM', 'Bom'), ('OT', 'Otimo'), ('NO', 'Nao')], default='GO', max_length=2)),
                ('reaction_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='perfis.Perfil')),
            ],
        ),
    ]
