# Generated by Django 2.1.5 on 2019-02-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190203_1032'),
        ('posts', '0011_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='compartilhado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhado', to='perfis.Perfil'),
        ),
    ]
