# Generated by Django 2.1.4 on 2019-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190209_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('fa fa-heart', 'Gostei'), ('fa fa-rocket', 'Vamos'), ('fa fa-microphone-slash', 'Horrivel'), ('fa fa-check-circle', 'Quero'), ('fa fa-star', 'Legal'), ('fa fa-map-marker', 'Vou'), ('fa fa-check', 'Bom'), ('fa fa-handshake', 'Otimo'), ('fa fa-times', 'Nao')], default='fa fa-heart', max_length=30),
        ),
    ]
