# Generated by Django 2.1.4 on 2019-01-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
