# Generated by Django 2.1.4 on 2019-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190107_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
