# Generated by Django 2.1.4 on 2018-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='convidavel',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
