# Generated by Django 2.1.4 on 2018-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_convidavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
