# Generated by Django 2.1.4 on 2018-12-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_perfil_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='justificativa',
            field=models.TextField(null=True),
        ),
    ]
