# Generated by Django 2.1.4 on 2018-12-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_perfil_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
