# Generated by Django 2.1.4 on 2018-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_perfil_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='error_mensage',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
