# Generated by Django 2.1.4 on 2018-12-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_perfil_error_mensage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
