# Generated by Django 2.1.4 on 2019-01-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_auto_20181229_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
