# Generated by Django 2.1.4 on 2019-01-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_auto_20190101_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to='perfis.Perfil')),
            ],
        ),
    ]
