# Generated by Django 2.1.4 on 2019-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190203_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type_message',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
